@base_url=http://localhost:8080
@channel_id=1358762570651140216

### channel
GET {{base_url}}/channel/{{channel_id}}/messages

### rss

GET {{base_url}}/rss/entries

### summary
GET {{base_url}}/misskey/summary